version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./models:/app/models

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: python dashboard/main.py
    ports:
      - "8050:8050"
    env_file:
      - .env
    volumes:
      - ./dashboard:/app/dashboard
      - ./data:/app/data
      - ./models:/app/models 